name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build App
        run: scripts/buildprod.sh
